import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Jim_Nightshade } from "next/font/google";
import { Julius_Sans_One } from "next/font/google";
import { Jura } from "next/font/google";

import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/server/auth";
import Dashboard from "@/components/Dashboard";
import useFonts from "@/hooks/useFonts";
import { Providers } from "@/redux/provider";

export const metadata: Metadata = {
  title: "Trader Keys",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  login: React.ReactNode;
  modal: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  const { Jim, julius } = useFonts();
  // console.log("ovd", session);

  if (!session) {
    return (
      <html lang='en'>
        <body className={Jim.className}>{props.login}</body>
      </html>
    );
  }
  return (
    <html lang='en'>
      <Providers>
        <body className={`flex ${Jim.className}`}>
          <Dashboard session={session} />
          <div className={` ${julius.className} flex-1`}>{props.children}</div>
        </body>
      </Providers>
    </html>
  );
}
