import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Jim_Nightshade } from "next/font/google";

import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/server/auth";
import Dashboard from "@/components/Dashboard";

const inter = Inter({ subsets: ["latin"] });
const Jim = Jim_Nightshade({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trader Keys",
  description: "Generated by create next app",
};

export default async function RootLayout(props: {
  children: React.ReactNode;
  login: React.ReactNode;
  soft: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  // console.log("ovd", session);

  if (!session) {
    return (
      <html lang='en'>
        <body className={Jim.className}>{props.login}</body>
      </html>
    );
  }
  return (
    <html lang='en'>
      <body className={`flex ${Jim.className}`}>
        <Dashboard session={session} />
        <div className='w-[75%]'>{props.children}</div>
      </body>
    </html>
  );
}
